title: Markus Junnola # your name (or website title) here
logo: "/images/omakuva.PNG" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Strategic Finance and Business Analytics student 
  <br><br>
  Here you can see some of my past projects. Please have a look and leave a comment!
  <br><br>
  <a href="https://www.linkedin.com/in/mjunnola">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
